name: hexo-blog-deploy

on:
  push:
    branches:
      - main

env:
  GIT_USER: yeliqin666
  GIT_EMAIL: 15965115971@163.com
  DEPLOY_REPO: yeliqin666/yeliqin666.github.io
  DEPLOY_BRANCH: master

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [19.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_SECRET: ${{secrets.HEXO_DEPLOY_SECRET}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"

          # 配置私钥，否则无法访问部署库，提示 git@github.com: Permission denied (publickey).
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_SECRET" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # 设置用户名和邮箱，否则提示 Please tell me who you are.
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Install dependencies
        run: |
          npm install
          npm install hexo-deployer-git --save
          # 全局搜索插件
          npm install hexo-generator-searchdb --save
          
      - name: Deploy hexo
        run: |
          npm run deploy

